In [2]:
import pandas as pd
import numpy as np
import psycopg2
from sqlalchemy import create_engine

In [3]:
df_factures = pd.read_csv("Factures.csv")
df_devis    = pd.read_csv("Devis.csv")
df_produits = pd.read_csv("Produits.csv")

In [4]:

display(df_factures.head(3))

display(df_devis.head(3))

display(df_produits.head(3))

,client_id,nom_client,adresse_client,facture_id,date_facture,produit_id,nom_produit,quantité,prix_unitaire
0,667,Johnathan Erickson,"54552 Michele Port Apt. 363, West Melissa, NY ...",64371,2023-12-21,23504,may somebody,4,223.91
1,667,Johnathan Erickson,"54552 Michele Port Apt. 363, West Melissa, NY ...",73886,2024-07-02,20230,maintain finish,5,37.39
2,667,Johnathan Erickson,"54552 Michele Port Apt. 363, West Melissa, NY ...",94525,2024-06-20,91241,Republican police,3,442.29

,client_id,nom_client,adresse_client,devis_id,date_devis,produit_id,nom_produit,quantité,prix_unitaire
0,667,Johnathan Erickson,"54552 Michele Port Apt. 363, West Melissa, NY ...",54834,2023-12-20,74698,activity both,5,912.19
1,667,Johnathan Erickson,"54552 Michele Port Apt. 363, West Melissa, NY ...",54834,2023-12-20,49358,west build,3,812.37
2,667,Johnathan Erickson,"54552 Michele Port Apt. 363, West Melissa, NY ...",76841,2024-06-22,66829,indicate glass,2,655.22

   produit_id      nom_produit     catégorie  prix_unitaire
0       98054           if top        Maison         973.01
1       83028     impact reach  Informatique         880.32
2       64717  together system        Jardin         136.24

## Exploration des fichiers vu de la shape des doublons et des données manquantes

In [5]:
print("Factures :", df_factures.shape)
print("Devis    :", df_devis.shape)
print("Produits :", df_produits.shape)

Factures : (5975, 9)
Devis    : (3999, 9)
Produits : (100, 4)

In [6]:
print("    FACTURES")
print(df_factures.dtypes)

print("\n   DEVIS ")
print(df_devis.dtypes)

print("\n   PRODUITS ")
print(df_produits.dtypes)

    FACTURES
client_id           int64
nom_client            str
adresse_client        str
facture_id          int64
date_facture          str
produit_id          int64
nom_produit           str
quantité            int64
prix_unitaire     float64
dtype: object

   DEVIS
client_id           int64
nom_client            str
adresse_client        str
devis_id            int64
date_devis            str
produit_id          int64
nom_produit           str
quantité            int64
prix_unitaire     float64
dtype: object

   PRODUITS
produit_id         int64
nom_produit          str
catégorie            str
prix_unitaire    float64
dtype: object

In [7]:

print(df_factures.isnull().sum())

print(df_devis.isnull().sum())

print(df_produits.isnull().sum())

client_id         0
nom_client        0
adresse_client    0
facture_id        0
date_facture      0
produit_id        0
nom_produit       0
quantité          0
prix_unitaire     0
dtype: int64
client_id         0
nom_client        0
adresse_client    0
devis_id          0
date_devis        0
produit_id        0
nom_produit       0
quantité          0
prix_unitaire     0
dtype: int64
produit_id       0
nom_produit      0
catégorie        0
prix_unitaire    0
dtype: int64

In [8]:
# pour compter les doublons
print("Factures :", df_factures.duplicated().sum())
print("Devis    :", df_devis.duplicated().sum())
print("Produits :", df_produits.duplicated().sum())

Factures : 11
Devis    : 7
Produits : 0

In [9]:
# suppression des doublons
df_factures = df_factures.drop_duplicates()
df_devis    = df_devis.drop_duplicates()

## Nottyage des fichiers en enlevant les accent ( renommer les colonnes )

In [10]:
df_produits = df_produits.rename(columns={"catégorie": "categorie"})
df_factures = df_factures.rename(columns={"quantité": "quantite"})
df_devis    = df_devis.rename(columns={"quantité": "quantite"})
df_factures["date_facture"] = pd.to_datetime(df_factures["date_facture"])
df_devis["date_devis"]      = pd.to_datetime(df_devis["date_devis"])

In [11]:
print("Doublons Factures :", df_factures.duplicated().sum())
print("Doublons Devis    :", df_devis.duplicated().sum())
print("Doublons Produits :", df_produits.duplicated().sum())

print("\nValeurs manquantes Factures :\n", df_factures.isnull().sum())
print("\nValeurs manquantes Devis    :\n", df_devis.isnull().sum())
print("\nValeurs manquantes Produits :\n", df_produits.isnull().sum())

Doublons Factures : 0
Doublons Devis    : 0
Doublons Produits : 0

Valeurs manquantes Factures :
 client_id         0
nom_client        0
adresse_client    0
facture_id        0
date_facture      0
produit_id        0
nom_produit       0
quantite          0
prix_unitaire     0
dtype: int64

Valeurs manquantes Devis    :
 client_id         0
nom_client        0
adresse_client    0
devis_id          0
date_devis        0
produit_id        0
nom_produit       0
quantite          0
prix_unitaire     0
dtype: int64

Valeurs manquantes Produits :
 produit_id       0
nom_produit      0
categorie        0
prix_unitaire    0
dtype: int64

## Corriger les types pour correspondre à ton schéma

In [13]:
# client_id en entier
df_factures["client_id"] = df_factures["client_id"].astype(int)
df_devis["client_id"]    = df_devis["client_id"].astype(int)

# facture_id, devis_id, produit_id en string
df_factures["facture_id"]  = df_factures["facture_id"].astype(str)
df_factures["produit_id"]  = df_factures["produit_id"].astype(str)

df_devis["devis_id"]    = df_devis["devis_id"].astype(str)
df_devis["produit_id"]  = df_devis["produit_id"].astype(str)

df_produits["produit_id"] = df_produits["produit_id"].astype(str)

# Extraction des tables pour la base psql

In [14]:
df_client = pd.concat([df_factures[["client_id", "nom_client", "adresse_client"]],
                        df_devis[["client_id", "nom_client", "adresse_client"]]])

df_client = df_client.drop_duplicates(subset="client_id").sort_values("client_id").reset_index(drop=True)

print(df_client.shape)
display(df_client.head())

(1000, 3)

,client_id,nom_client,adresse_client
0,154,Jessica Bright,"0278 Cohen Cliff, North Johnberg, NV 44191"
1,324,Michael Shepherd,"Unit 4986 Box 6052, DPO AP 11370"
2,355,Tina Cooper,"3283 Peters Squares, Port Teresa, MO 75735"
3,365,James Coffey,"8970 Martinez Cliffs Suite 963, New Nicholasbe..."
4,403,Samantha Hill,"6938 Johnson Flats Apt. 903, South Andrew, MN ..."

In [15]:
df_produit = df_produits[["produit_id", "nom_produit", "categorie", "prix_unitaire"]].reset_index(drop=True)

print(df_produit.shape)
display(df_produit.head())

(100, 4)

  produit_id      nom_produit     categorie  prix_unitaire
0      98054           if top        Maison         973.01
1      83028     impact reach  Informatique         880.32
2      64717  together system        Jardin         136.24
3      74698    activity both  Électronique         912.19
4      13433   positive after        Maison         154.64

In [16]:
df_facture = df_factures[["facture_id", "date_facture", "client_id"]].drop_duplicates(subset="facture_id").sort_values("facture_id").reset_index(drop=True)

print(df_facture.shape)
display(df_facture.head())

(2985, 3)

  facture_id date_facture  client_id
0      10020   2023-12-09      61947
1      10097   2024-05-29      43297
2      10102   2024-05-14      73998
3      10114   2024-06-11      94004
4      10211   2024-04-01      36492

In [17]:
df_devis_h = df_devis[["devis_id", "date_devis", "client_id"]].drop_duplicates(subset="devis_id").sort_values("devis_id").reset_index(drop=True)

print(df_devis_h.shape)
display(df_devis_h.head())

(1974, 3)

  devis_id date_devis  client_id
0    10221 2024-06-21      51189
1    10287 2024-09-14      75060
2    10342 2023-11-12      50028
3    10396 2024-05-01      96088
4    10420 2023-11-12      35033

In [18]:
df_ligne_facture = df_factures[["facture_id", "produit_id", "quantite", "prix_unitaire"]].reset_index(drop=True)

print(df_ligne_facture.shape)
display(df_ligne_facture.head())

(5964, 4)

  facture_id produit_id  quantite  prix_unitaire
0      64371      23504         4         223.91
1      73886      20230         5          37.39
2      94525      91241         3         442.29
3      94525       9868         2         882.40
4      94525      22733         5         790.71

In [19]:
df_ligne_devis = df_devis[["devis_id", "produit_id", "quantite", "prix_unitaire"]].reset_index(drop=True)

print(df_ligne_devis.shape)
display(df_ligne_devis.head())

(3992, 4)

  devis_id produit_id  quantite  prix_unitaire
0    54834      74698         5         912.19
1    54834      49358         3         812.37
2    76841      66829         2         655.22
3    76841      12041         3         550.40
4    66558      53539         4         458.26

## connexion à la bdd

In [ ]:
db_co = create_engine("postgresql+psycopg2://postgres:motdepasse@localhost:5432/entreprise")

In [23]:
#insertion des clients 
df_client.to_sql("client", db_co, if_exists="append", index=False)
print("clients insérés :", len(df_client))

clients insérés : 1000

In [24]:
df_produit.to_sql("produit", db_co, if_exists="append", index=False)
print("produits insérés :", len(df_produit))

produits insérés : 100

In [25]:
df_facture.to_sql("facture", db_co, if_exists="append", index=False)
print("factures insérées :", len(df_facture))

factures insérées : 2985

In [26]:
df_devis_h.to_sql("devis", db_co, if_exists="append", index=False)
print("devis insérés :", len(df_devis_h))

devis insérés : 1974

In [27]:
df_ligne_facture.to_sql("ligne_facture", db_co, if_exists="append", index=False)
print("lignes facture insérées :", len(df_ligne_facture))

lignes facture insérées : 5964

In [28]:
df_ligne_devis.to_sql("ligne_devis", db_co, if_exists="append", index=False)
print("lignes devis insérées :", len(df_ligne_devis))

lignes devis insérées : 3992